// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import pubsub "github.com/chainspace/blockmania/pubsub"

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Server) Close() {
	_m.Called()
}

// Publish provides a mock function with given fields: tx
func (_m *Server) Publish(tx []byte) {
	_m.Called(tx)
}

// RegisterNotifier provides a mock function with given fields: n
func (_m *Server) RegisterNotifier(n pubsub.Notifier) {
	_m.Called(n)
}
